---
title: "Fixed effects and Random effects"
author: "Anna Werner & Susumu Shikano"
date: "`r Sys.Date()`"
output: html_document
---


```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load data

```{r}
load("Data/analysis_dat.RData")
```



## Switch for party selection

```{r}

## Do not select only one party. This won't work!

party.selection <- c(1:6) # C S A F L G
#party.selection <- c(3:6) # ohne C und S
#party.selection <- c(1:2) # nur C und S
#party.selection <- c(1:4,6) # ohne Linke

```


```{r}
all.abs.votes <- all.abs.votes[,party.selection,,,]
all.treat     <- all.treat[,party.selection,,]

```



### Election results

We first compute the relative vote shares: 

```{r}

  all.rel.votes <-  all.abs.votes/all.abs.total[,rep(3,length(party.selection)),,,] 
  # If one uses valid votes: rep(3,6)
  # If one uses all voters: rep(2,6)
  # If one uses all eligible citizens: rep(1,6)

  # We delete the past results
  all.rel.votes <- all.rel.votes[,,,,1]

```



### Treatment

```{r}

all.treat.dummy <- all.treat
all.treat.dummy[all.treat.dummy>0] <- 1

table(all.treat.dummy)



```

## index array

Year index

```{r}
year.index <- all.treat.dummy

year.index[,,,1] <- 2021
year.index[,,,2] <- 2017
year.index[,,,3] <- 2013
year.index[,,,4] <- 2009
year.index[,,,5] <- 2005
year.index[,,,6] <- 2002

table(year.index)

```

Party index

```{r}
party.index <- all.treat.dummy

party.labels <- c("CDU","SPD","AFD","FDP","LIN","GRU")[party.selection]
for (i.party in 1:length(party.selection)){
  party.index[,i.party,,] <- party.labels[i.party]
}

table(party.index)
```

Modification of wahlkreis index array

```{r}
all.wkr.index <- all.wkr.index[,party.selection,,]

```

# Fixed effect models


```{r}

for (i.smdpr in 1:2){ # Loop over Erst- and Zweitstimme

  all.results <- vector("list",3) # empty list to store the results

  votes.in.array <- all.rel.votes[,,i.smdpr,1:5]
  votes <- c(all.rel.votes[,,i.smdpr,1:5] )
  last.votes <- c(all.rel.votes[,,i.smdpr,2:6] )
  treat <- c(all.treat.dummy[,,i.smdpr,1:5] )
  year  <- as.factor(c(year.index[,,i.smdpr,1:5] ))
  party <- as.factor(c(party.index[,,i.smdpr,1:5] ))
  district <- as.factor(c(all.wkr.index[,,i.smdpr,1:5]))
  cross.treat <- c(all.treat.dummy[,,c(2,1)[i.smdpr],1:5] )

  #district[district==337] <- 15 # Merkel
  #district[district==388] <- 61 # Potsdam
  #district[district==364] <- 61 # Potsdam
  #district[district==366] <- 14 # Bartsch
  
  lm.dat <- as.data.frame(votes)
  lm.dat <- cbind(lm.dat,treat,year,party,district,cross.treat)
  
  ## Model with year and party fixed effects.
  print(c("Erststimme (H1a)","Zweitstimme  (H1b)")[i.smdpr])
  options(max.print=100)
  print(summary(lm.out <- lm(votes~ treat + last.votes+ year * party + district*party )))

  all.results[[1]] <- lm.out
  
  ## Model with cross treatment (contamination)

  print(c("Contamination Erststimme (H2b)","Contamination Zweitstimme  (H2a)")[i.smdpr])
  print(summary(lm.out <- lm(votes~ treat + last.votes +cross.treat + year * party + district*party)))
  
  all.results[[2]] <- lm.out
  
  all.results[[3]] <- lm.dat
  all.results[[4]] <- votes.in.array
  
  if (i.smdpr==1) all.results.smd <- all.results
  if (i.smdpr==2) all.results.pr <- all.results
}

options(max.print=10000)
```

## Some diagnostic checks


Checking residuals

```{r}

results.te <- all.results.smd[[1]]

#plot(results.te)


data.te <- all.results.smd[[3]]

data.te <- data.te[!is.na(data.te[,1]),]
dim(data.te)

residuals <- residuals(results.te)
predicted <- predict(results.te)

length(residuals)


plot(residuals ~ data.te$treat)
tapply(residuals , as.factor( data.te$treat),mean)



```

### Plotting the actual votes, predicted votes and residuals for treated district

```{r}
par(mfrow=c(1,2))

plot(data.te$votes[data.te$treat==1] ~ predicted[data.te$treat==1],
     xlab="Predicted",ylab="Actual")
abline(coef=c(0,1),lty=2)
labels <- data.te[data.te$treat==1,3:5]

text( predicted[data.te$treat==1],data.te$votes[data.te$treat==1] ,
     rownames(data.te)[data.te$treat==1],
     pos=1,cex=0.7)


plot(residuals[data.te$treat==1] ~ predicted[data.te$treat==1],
     xlab="Predicted",ylab="Rersiduals")

labels <- data.te[data.te$treat==1,3:5]

text( predicted[data.te$treat==1],residuals[data.te$treat==1] ,
     rownames(data.te)[data.te$treat==1],
     pos=1,cex=0.7)


labels

```



```{r}

wkr.fe <- coefficients(results.te)
wkr.fe <- wkr.fe[grep("district",names(wkr.fe))]

hist(wkr.fe)

wkr.fe[order(wkr.fe)][1:5]

wkr.fe[order(wkr.fe,decreasing=TRUE)][1:5]

```

### Exogeneoity

```{r}

options(max.print=100)
# District candidacy: Treatment for SMD
summary(lm(c(all.treat.dummy[,,1,1:5]) ~ c(all.rel.votes[,,1,2:6])+
                                          c(party.index[,,1,1:5])*
                                           as.factor(c(all.wkr.index[,,1,1:5]))))

# PR list candidacy: Treatment for PR
summary(lm(c(all.treat.dummy[,,2,1:5]) ~ c(all.rel.votes[,,2,2:6])+
                                          c(party.index[,,2,1:5])*
                                           as.factor(c(all.wkr.index[,,2,1:5]))))
options(max.print=10000)

```




