---
title: "Some descriptive analysis"
author: "Anna Werner & Susumu Shikano"
date: "`r Sys.Date()`"
output: html_document
---


```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stargazer)
```


## Load data

```{r}
load("Data/analysis_dat.RData")
```


## Some preparation

all.abs.votes has 5 dimensions:

- 299 districts
- 6 parties
- tier: FPTP or PR
- 6 elections
- current or last elections


```{r}
party.selection <- c(1:6) 
vote.denom <- 1


all.abs.votes <- all.abs.votes[,party.selection,,,]
all.rel.votes <-  all.abs.votes/all.abs.total[,rep(vote.denom,length(party.selection)),,,] 

```


## Closeness of district races



```{r}
library(kit)


relevant.votes <- all.rel.votes[,,1,,1] 

top.share <- apply(relevant.votes,c(1,3),max,na.rm=T)

second.best <- function(x) x[topn(x,2)[2]]

second.share <- apply(relevant.votes,c(1,3),second.best)

margin <- top.share - second.share

hist(c(margin),br=seq(0,.5,by=0.01))

median(margin)


table(margin<0.015)
mean(margin<0.01)
mean(margin<0.015)
mean(margin<0.02)

```












