---
title: "Table_Generator"
author: "Anna Werner"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Reading the output

Switch

```{r}

lang.switch <- 2 # 1: German, 2: English

```






### Regression tables with robust SE

Reading results

```{r }
library(stargazer)

spill.over.switch <- 0
vote.denom <- 1

for (turnout.switch in 0:1){
    for (party.selec.switch in 1:3){
    load(
      file=paste0("Data/Estimation_Results_PSelect",party.selec.switch,
                 "_denom",vote.denom,
                 c("","_spillover")[spill.over.switch+1],
                 c("","_turnout")[turnout.switch+1],
                 ".RData"))
    
      if (turnout.switch==0){ 
          if (party.selec.switch==1){
            lm.pr <- all.results.pr[[1]]
            se.pr <- all.results.pr[[5]]
            lm.smd <- all.results.smd[[1]]
            se.smd <- all.results.smd[[5]]
          }
          
          if (party.selec.switch==2){
            lm.pr.cs <- all.results.pr[[1]]
            se.pr.cs <- all.results.pr[[5]]
            lm.smd.cs <- all.results.smd[[1]]
            se.smd.cs <- all.results.smd[[5]]
          }
          
          if (party.selec.switch==3){
            lm.pr.aflg <- all.results.pr[[1]]
            se.pr.aflg <- all.results.pr[[5]]
            lm.smd.aflg <- all.results.smd[[1]]
            se.smd.aflg <- all.results.smd[[5]]
          }
      }else{
          if (party.selec.switch==1){
            lm.smd.to <- all.results.smd[[1]]
            se.smd.to <- all.results.smd[[5]]
          }
          
          if (party.selec.switch==2){
            lm.smd.cs.to <- all.results.smd[[1]]
            se.smd.cs.to <- all.results.smd[[5]]
          }
          
          if (party.selec.switch==3){
            lm.smd.aflg.to <- all.results.smd[[1]]
            se.smd.aflg.to <- all.results.smd[[5]]
          }
        
      } 
    }
}


```



```{r}
## DV: Erststimme
print(c("DV: Erststimme"))
stargazer(lm.smd, lm.smd.cs, lm.smd.aflg,
          title = c("Direktkandidatur und Listenplatzierung auf Erststimmenergebnis",
                    "Effects on the FPTP vote shares")[lang.switch],
          #dep.var.labels = "Unterschied im Erststimmenanteil",
          se = list(se.smd, se.smd.cs, se.smd.aflg),
          column.labels = cbind(c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
                            c("All parties","Major parties","Minor parties"))[,lang.switch],
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          #single.row=TRUE,
          font.size = "small",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("year2009:partyCDU", "year2013:partyCDU", "year2017:partyCDU", "year2021:partyCDU",
                    "year2009:partySPD", "year2013:partySPD", "year2017:partySPD", "year2021:partySPD",
                    "year2009:partyFDP", "year2013:partyFDP", "year2017:partyFDP", "year2021:partyFDP",
                    "year2009:partyLIN", "year2013:partyLIN", "year2017:partyLIN", "year2021:partyLIN",
                    "year2009:partyGRU", "year2013:partyGRU", "year2017:partyGRU", "year2021:partyGRU"),
          covariate.labels = cbind(c("Direktkandidatur",
                               "Listenplatzierung", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Konstante"
                              ),
                              c("Discrict",
                               "Party list", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Green", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Intercept"
                              )
                              )[,lang.switch],
          #ci = TRUE,
          #notes.label = "Anmerkung",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = c("Hier werden Anmerkungen stehen",
                    "Note: The robust HAC standard errors are shown in brackets.")[lang.switch],#,
          style = "apsr",
          type = "latex",
          out = c("Table_1.html")
          )
```





```{r}
## DV: Zweitstimme
print(c("DV: Zweitstimme"))
stargazer(lm.pr, lm.pr.cs, lm.pr.aflg,
          title = c("Listenplatzierung und Direktkandidatur auf Zweitstimmenergebnis",
                    "Effects on the PR vote shares")[lang.switch],
          #dep.var.labels = "Abhängige Variable: Unterschied im Zweitstimmenanteil",
          se = list(se.pr, se.pr.cs, se.pr.aflg),
          column.labels = cbind(c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
                            c("All parties","Major parties","Minor parties"))[,lang.switch],
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          #single.row=TRUE,
          font.size = "small",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c(12:31),
            #c("year2009:partyCDU" : "year2021:partyGRU"),
          covariate.labels = cbind(c("Direktkandidatur",
                               "Listenplatzierung", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Konstante"
                              ),
                              c("Discrict",
                               "Party list", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Green", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Intercept"
                              )
                              )[,lang.switch],
          #ci = TRUE,
          notes.label = "Anmerkung:",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = c("Hier werden Anmerkungen stehen",
                    "Note: The robust HAC standard errors are shown in brackets.")[lang.switch],#,
          style = "apsr",
          type = "latex",
          out = c("Table_2.html")
          )
```



```{r}
## DV: Turnout
print(c("DV: Turnout"))
stargazer(lm.smd.to, lm.smd.cs.to, lm.smd.aflg.to,
          title = c("Direktkandidatur und Listenplatzierung auf Wahlbeteiligung",
                    "Effects on turnout")[lang.switch],
          #dep.var.labels = "Unterschied im Erststimmenanteil",
          se = list(se.smd, se.smd.cs, se.smd.aflg),
          column.labels = cbind(c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
                            c("All parties","Major parties","Minor parties"))[,lang.switch],
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          #single.row=TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("year2009:partyCDU", "year2013:partyCDU", "year2017:partyCDU", "year2021:partyCDU",
                    "year2009:partySPD", "year2013:partySPD", "year2017:partySPD", "year2021:partySPD",
                    "year2009:partyFDP", "year2013:partyFDP", "year2017:partyFDP", "year2021:partyFDP",
                    "year2009:partyLIN", "year2013:partyLIN", "year2017:partyLIN", "year2021:partyLIN",
                    "year2009:partyGRU", "year2013:partyGRU", "year2017:partyGRU", "year2021:partyGRU"),
          covariate.labels = cbind(c("Direktkandidatur",
                               "Listenplatzierung", 
                               "2009", "2013", "2017", "2021", 
                               #"CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Konstante"
                              ),
                              c("Discrict",
                               "Party list", 
                               "2009", "2013", "2017", "2021", 
                               #"CDU", "SPD", "FDP", "Linke", "Green", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Intercept"
                              )
                              )[,lang.switch],
          #ci = TRUE,
          #notes.label = "Anmerkung",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = c("Hier werden Anmerkungen stehen",
                    "Note: The robust HAC standard errors are shown in brackets.")[lang.switch],#,
          style = "apsr",
          type = "html",
          out = c("Table_1.html")
          )
```



### Regression tables Appendix

## Diagnostics II: Exogeneity of the treatment

# ```{r}
# load("Data/Exogeneity_Results_PSelect1_denom1.RData")
# lm.t1.pr <- all.results.t1.pr[[1]]
# se.t1.pr <- all.results.t1.pr[[5]]
# lm.t1.smd <- all.results.t1.smd[[1]]
# se.t1.smd <- all.results.t1.smd[[5]]
# 
# load("Data/Estimation_Results_PSelect2_denom1.RData")
# lm.t1.pr.cs <- all.results.t1.pr[[1]]
# se.t1.pr.cs <- all.results.t1.pr[[5]]
# lm.t1.smd.cs <- all.results.t1.smd[[1]]
# se.t1.smd.cs <- all.results.t1.smd[[5]]
# 
# load("Data/Estimation_Results_PSelect3_denom1.RData")
# lm.t1.pr.aflg <- all.results.t1.pr[[1]]
# se.t1.pr.aflg <- all.results.t1.pr[[5]]
# lm.t1.smd.aflg <- all.results.t1.smd[[1]]
# se.t1.smd.aflg <- all.results.t1.smd[[5]]
# ```


```{r}
library(stargazer)

spill.over.switch <- 0
vote.denom <- 1

#for (turnout.switch in 0:1){
    for (party.selec.switch in 1:3){
    load(
      file=paste0("Data/Exogeneity_Results_PSelect",party.selec.switch,
                 "_denom",vote.denom,
                 ".RData"))
    
      #if (turnout.switch==0){ 
          if (party.selec.switch==1){
            lm.t1.pr <- all.results.t1.pr[[1]]
            se.t1.pr <- all.results.t1.pr[[5]]
            lm.t1.smd <- all.results.t1.smd[[1]]
            se.t1.smd <- all.results.t1.smd[[5]]
          }
          
          if (party.selec.switch==2){
            lm.t1.pr.cs <- all.results.t1.pr[[1]]
            se.t1.pr.cs <- all.results.t1.pr[[5]]
            lm.t1.smd.cs <- all.results.t1.smd[[1]]
            se.t1.smd.cs <- all.results.t1.smd[[5]]
          }
          
          if (party.selec.switch==3){
            lm.t1.pr.aflg <- all.results.t1.pr[[1]]
            se.t1.pr.aflg <- all.results.t1.pr[[5]]
            lm.t1.smd.aflg <- all.results.t1.smd[[1]]
            se.t1.smd.aflg <- all.results.t1.smd[[5]]
          }
     # }else{
          # if (party.selec.switch==1){
          #   lm.t1.smd.to <- all.results.t1.smd[[1]]
          #   se.t1.smd.to <- all.results.t1.smd[[5]]
          # }
          # 
          # if (party.selec.switch==2){
          #   lm.t1.smd.cs.to <- all.results.t1.smd[[1]]
          #   se.t1.smd.cs.to <- all.results.t1.smd[[5]]
          # }
          # 
          # if (party.selec.switch==3){
          #   lm.t1.smd.aflg.to <- all.results.t1.smd[[1]]
          #   se.t1.smd.aflg.to <- all.results.t1.smd[[5]]
          # }
        
      #} 
    #}
}


```

## Exogeneity with vote share based on eligible citizen (denom1)
```{r}
## DV: Erststimme
print(c("DV: Erststimme"))
stargazer(lm.t1.smd, lm.t1.smd.cs, lm.t1.smd.aflg,
          title = "Test auf Exogenität bei abhängiger Variable Erststimmenanteile nach Wahlberechtigten",
          #dep.var.labels = "Unterschied im Erststimmenanteil",
          se = list(se.t1.smd, se.t1.smd.cs, se.t1.smd.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = FALSE,
          align = TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("as.factor(year)2:as.factor(party)2", "as.factor(year)3:as.factor(party)2",    
                   "as.factor(year)4:as.factor(party)2",
                   "as.factor(year)2:as.factor(party)3", "as.factor(year)3:as.factor(party)3", 
                   "as.factor(year)4:as.factor(party)3",
                   "as.factor(year)2:as.factor(party)4", "as.factor(year)3:as.factor(party)4", 
                   "as.factor(year)4:as.factor(party)4",
                   "as.factor(year)2:as.factor(party)5", "as.factor(year)3:as.factor(party)5", 
                   "as.factor(year)4:as.factor(party)5",
                   "as.factor(year)2:as.factor(party)6", "as.factor(year)3:as.factor(party)6 ", 
                   "as.factor(year)4:as.factor(party)6"),
          #covariate.labels = c("Direktkandidatur",
                              # "Direktkdt. Folgejahr",
                              # "Listenplatzierung",
                              # "Listenplz. Folgejahr",
                              # "2009", "2013", "2017", "2021", 
                             #  "CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                              # "Konstante"
                             # ),
          notes.label = "Anmerkung:",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "Hier werden Anmerkungen stehen"#,
          #style = "apsr",
          #type = "html",
          #out = c("Exg_table_1.html")
          )

## DV: Zweitstimme
print(c("DV: Zweitstimme"))
stargazer(lm.t1.pr, lm.t1.pr.cs, lm.t1.pr.aflg,
          title = "Test auf Exogenität bei abhängiger Variable Zweitstimmenanteile nach Wahlberechtigten",
          #dep.var.labels = "Abhängige Variable: Unterschied im Zweitstimmenanteil",
          se = list(se.t1.pr, se.t1.pr.cs, se.t1.pr.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = FALSE,
          align = TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("as.factor(year)2:as.factor(party)2", "as.factor(year)3:as.factor(party)2", 
                   "as.factor(year)4:as.factor(party)2",
                   "as.factor(year)2:as.factor(party)3", "as.factor(year)3:as.factor(party)3", 
                   "as.factor(year)4:as.factor(party)3",
                   "as.factor(year)2:as.factor(party)4", "as.factor(year)3:as.factor(party)4", 
                   "as.factor(year)4:as.factor(party)4",
                   "as.factor(year)2:as.factor(party)5", "as.factor(year)3:as.factor(party)5", 
                   "as.factor(year)4:as.factor(party)5",
                   "as.factor(year)2:as.factor(party)6", "as.factor(year)3:as.factor(party)6 ", 
                   "as.factor(year)4:as.factor(party)6"),
          #covariate.labels = c("Listenplatzierung",
                              # "Listenplz. Folgejahr",
                              # "Direktkandidatur",
                              # "Direktkdt. Folgejahr",
                              # "2009", "2013", "2017", 
                              # "CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                              # "Konstante"
                              #),
          notes.label = "Anmerkung:",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "Hier werden Anmerkungen stehen"#,
          #style = "apsr",
          #type = "html",
          #out = c("Exg_table_2.html")
          )
```



### Robustness Check - Quasi-Incumbency

```{r }
library(stargazer)

load("Data/Estimation_Results_Incumb_PSelect1_denom1.RData")
lm.pr <- all.results.pr[[1]]
se.pr <- all.results.pr[[5]]
lm.smd <- all.results.smd[[1]]
se.smd <- all.results.smd[[5]]

load("Data/Estimation_Results_Incumb_PSelect2_denom1.RData")
lm.pr.cs <- all.results.pr[[1]]
se.pr.cs <- all.results.pr[[5]]
lm.smd.cs <- all.results.smd[[1]]
se.smd.cs <- all.results.smd[[5]]

load("Data/Estimation_Results_Incumb_PSelect3_denom1.RData")
lm.pr.aflg <- all.results.pr[[1]]
se.pr.aflg <- all.results.pr[[5]]
lm.smd.aflg <- all.results.smd[[1]]
se.smd.aflg <- all.results.smd[[5]]

```

```{r}
## DV: Erststimme
print(c("DV: Erststimme"))
stargazer(lm.smd, lm.smd.cs, lm.smd.aflg,
          title = "Direktkandidatur, gestaffelte Direktkandidatur und Listenplatzierung auf Erststimmenergebnis",
          #dep.var.labels = "Unterschied im Erststimmenanteil",
          se = list(se.smd, se.smd.cs, se.smd.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          #single.row=TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("year2009:partyCDU", "year2013:partyCDU", "year2017:partyCDU", "year2021:partyCDU",
                   "year2009:partySPD", "year2013:partySPD", "year2017:partySPD", "year2021:partySPD",
                   "year2009:partyFDP", "year2013:partyFDP", "year2017:partyFDP", "year2021:partyFDP",
                   "year2009:partyLIN", "year2013:partyLIN", "year2017:partyLIN", "year2021:partyLIN",
                   "year2009:partyGRU", "year2013:partyGRU", "year2017:partyGRU", "year2021:partyGRU"),
          covariate.labels = c("Direktkandidatur",
                               "Direktkandidatur gestaffelt",
                               "Listenplatzierung", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Grüne", 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Konstante"
                              ),
          #ci = TRUE,
          #notes.label = "Anmerkung",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "Hier werden Anmerkungen stehen"#,
          #style = "apsr",
          #type = "html",
          #out = c("Table_Incumb_1.html")
          )

## DV: Zweitstimme
print(c("DV: Zweitstimme"))
stargazer(lm.pr, lm.pr.cs, lm.pr.aflg,
          title = "Listenplatzierung, gestaffelte Listenplatzierung und Direktkandidatur auf Zweitstimmenergebnis",
          #dep.var.labels = "Abhängige Variable: Unterschied im Zweitstimmenanteil",
          se = list(se.pr, se.pr.cs, se.pr.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          #single.row=TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          omit = c("year2009:partyCDU", "year2013:partyCDU", "year2017:partyCDU", "year2021:partyCDU",
                    "year2009:partySPD", "year2013:partySPD", "year2017:partySPD", "year2021:partySPD",
                    "year2009:partyFDP", "year2013:partyFDP", "year2017:partyFDP", "year2021:partyFDP",
                    "year2009:partyLIN", "year2013:partyLIN", "year2017:partyLIN", "year2021:partyLIN",
                    "year2009:partyGRU", "year2013:partyGRU", "year2017:partyGRU", "year2021:partyGRU"),
          covariate.labels = c("Listenplatzierung",
                               "Listenplatzierung gestaffelt",
                               "Direktkandidatur", 
                               "2009", "2013", "2017", "2021", 
                               "CDU", "SPD", "FDP", "Linke", "Grüne"#, 
                              # "2009xCDU", "2013xCDU", "2017xCDU", "2021xCDU",
                              # "2009xSPD", "2013xSPD", "2017xSPD", "2021xSPD",
                              # "2009xFDP", "2013xFDP", "2017xFDP", "2021xFDP",
                              # "2009xLinke", "2013xLinke", "2017xLinke", "2021xLinke",
                              # "2009xGrüne", "2013xGrüne", "2017xGrüne", "2021xGrüne",
                               "Konstante"
                              ),
          #ci = TRUE,
          notes.label = "Anmerkung:",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "ier werden Anmerkungen stehen",
          style = "apsr",
          type = "html",
          out = c("Table_Incumb_2.html")
          )
```


### Robustness Check - Fixed Effects 

```{r}
load("Data/Estimation_Results_FE_PSelect1_denom1.RData")
lm.pr <- all.results.pr[[1]]
se.pr <- all.results.pr[[5]]
lm.smd <- all.results.smd[[1]]
se.smd <- all.results.smd[[5]]

load("Data/Estimation_Results_FE_PSelect2_denom1.RData")
lm.pr.cs <- all.results.pr[[1]]
se.pr.cs <- all.results.pr[[5]]
lm.smd.cs <- all.results.smd[[1]]
se.smd.cs <- all.results.smd[[5]]

load("Data/Estimation_Results_FE_PSelect3_denom1.RData")
lm.pr.aflg <- all.results.pr[[1]]
se.pr.aflg <- all.results.pr[[5]]
lm.smd.aflg <- all.results.smd[[1]]
se.smd.aflg <- all.results.smd[[5]]
```

```{r}
## DV: Erststimme
print(c("DV: Erststimme"))
stargazer(lm.smd, lm.smd.cs, lm.smd.aflg,
          title = "Direktkandidatur, Listenplatzierung und Vorjahresergebnisse auf Erststimmenergebnis",
          #dep.var.labels = "Unterschied im Erststimmenanteil",
          se = list(se.smd, se.smd.cs, se.smd.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          #omit.stat = c("f","adj.rsq"),
          keep = c(1:4),
          covariate.labels = c("Direktkandidatur",
                               "Listenplatzierung",
                               "Vorjahresergebnis"
                               #,"Konstante"
                               ),
          #ci = TRUE,
          #notes.label = "Anmerkung",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "Hier werden Anmerkungen stehen"#,
          #style = "apsr",
          #type = "html",
          #out = c("Table_FE2_1.html")
          )

## DV: Zweitstimme
print(c("DV: Zweitstimme"))
stargazer(lm.pr, lm.pr.cs, lm.pr.aflg,
          title = "Listenpräsenz, Direktkandidatur und Vorjahresergebnisse auf Zweitstimmenergebnis",
          #dep.var.labels = "Abhängige Variable: Unterschied im Zweitstimmenanteil",
          se = list(se.pr, se.pr.cs, se.pr.aflg),
          column.labels = c("Alle Parteien", "CDU/CSU und SPD", "Kleinere Parteien"),
          model.names = TRUE,
          model.numbers = TRUE,
          align = TRUE,
          font.size = "scriptsize",
          no.space = TRUE,
          keep = c(1:4),
          #omit.stat = c("f","adj.rsq"),
          covariate.labels = c("Listenplatzierung",
                               "Direktkandidatur",
                               "Vorjahresergebnis"
                               #,"Konstante"
                               ),
          notes.label = "Anmerkung:",
          star.cutoffs = c(0.05,0.01,0.001),
          notes.align = "l",
          notes = "Hier werden Anmerkungen stehen"#,
          #style = "apsr",
          #type = "html",
          #out = c("Table_FE2_2.html")
          )
```

