---
title: "Visualization_FD_Legacy_Replication_Full"
author: "Susumu Shikano"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Figures in the MPSA paper (replicated baseline + spillover + turnout)

```{r}
all.results <- NULL
legacy.results.dir <- "../Outputs/Estimation_Results_21/Legacy_Replication"
legacy.fig.dir <- "../Outputs/Estimation_Results_21/Legacy_Replication/Figures"
green.mask.switch <- 0 # 1: legacy split masking; 0: GRU always minor (_gruMinorOnly files)
green.mask.suffix <- c("_gruMinorOnly", "")[green.mask.switch + 1]
if (!dir.exists(legacy.fig.dir)) {
  dir.create(legacy.fig.dir, recursive = TRUE)
}
file.name.list <- dir(legacy.results.dir)

for (i.switch in 1:3) {
  for (i.turnout in 0:1) {
    for (i.spillover in 0:1) {
      file.name <- paste0(
        "Estimation_Results_PSelect",
        i.switch,
        "_denom1",
        c("", "_spillover")[i.spillover + 1],
        c("", "_turnout")[i.turnout + 1],
        green.mask.suffix,
        "_legacy_replication.RData"
      )

      if (!(file.name %in% file.name.list)) {
        next
      }

      load(paste0(legacy.results.dir, "/", file.name))

      for (i.tier in 1:2) {
        if (i.tier == 1) {
          temp.results <- all.results.smd
        } else {
          temp.results <- all.results.pr
        }
        rel.information <- temp.results[[2]][2:3, 1:2]
        treat.size <- apply(temp.results[[3]][, 2:3] != 0, 2, sum)
        treat.size <- rbind(treat.size, treat.size)
        rel.information <- cbind(i.turnout, i.spillover, i.switch, i.tier,
                                 rel.information, treat.size)
        all.results <- rbind(all.results, rel.information)
      }
    }
  }
}

all.results[rownames(all.results) == "cross.treat", "treat"] <-
  all.results[rownames(all.results) == "cross.treat", "cross.treat"]

all.results <- as.data.frame(all.results)
```

### Results based on Models 1 - 3

```{r, warning=FALSE}
for (i.turnout in 0:1) {
  data.tv <- all.results[all.results$i.switch <= 3, ]

  if (i.turnout == 0) {
    data.tv <- data.tv[data.tv$i.turnout == 0, ]
  } else {
    # Compare baseline vs turnout while excluding spillover variants
    data.tv <- data.tv[data.tv$i.spillover == 0, ]
  }

  data.tv <- rbind(
    data.tv[grep("cross", rownames(data.tv), invert = TRUE), ],
    data.tv[grep("cross", rownames(data.tv), invert = FALSE), ]
  )
  data.tv <- data.tv[order(data.tv$i.tier), ]

  data.tv$lower.b <- data.tv$Estimate - 1.96 * data.tv$`Std. Error`
  data.tv$upper.b <- data.tv$Estimate + 1.96 * data.tv$`Std. Error`

  y.range <- range(c(data.tv$lower.b, data.tv$upper.b), na.rm = TRUE)
  y.range[2] <- y.range[2] + 0.02
  y.range[1] <- y.range[1] - 0.01

  data.tv <- rbind(data.tv[1:6, ], NA, data.tv[7:12, ], NA,
                   data.tv[13:18, ], NA, data.tv[19:24, ])

  title <- paste0(
    "All_Estimated_Effects_replicated",
    c("", "_on_Turnout")[i.turnout + 1],
    green.mask.suffix
  )

  pdf(file = paste0(legacy.fig.dir, "/", title, ".pdf"), width = 8, height = 5.5, pointsize = 13)

  if (i.turnout == 0) {
    plot.switch <- data.tv$i.spillover
  } else {
    plot.switch <- data.tv$i.turnout
  }

  plot(data.tv$Estimate, axes = FALSE,
       xlab = "", ylab = "Effect on vote share",
       ylim = y.range, xlim = c(0, nrow(data.tv) + 1),
       pch = 16, col = c("black", "grey")[plot.switch + 1], lwd = 1.5)

  data.tv$i.switch[is.na(data.tv$i.switch)] <- 0
  for (i.party in 1:nrow(data.tv)) {
    lines(c(i.party, i.party), c(data.tv$lower.b[i.party], data.tv$upper.b[i.party]),
          lty = 1, lwd = 2.5, col = c("black", "grey")[plot.switch[i.party] + 1])
  }

  axis(1, labels = FALSE, at = which(plot.switch == 0))
  axis(2)
  abline(h = 0, lty = 2)

  data.tv$i.switch[data.tv$i.switch == 0] <- NA
  data.tv$i.switch[plot.switch == 1] <- NA

  text(x = 1:nrow(data.tv), y = par("usr")[3] - 0.005,
       labels = c("All", "Major", "Minor")[data.tv$i.switch],
       xpd = NA, srt = 35, adj = 0.8, cex = 1.1)

  text(6, y.range[2] - 0.01,
       c("Effects on FPTP vote share", "Effects on FPTP vote/turnout")[i.turnout + 1], pos = 3)
  text(21, y.range[2] - 0.01,
       c("Effects on PR vote share", "Effects on PR vote/turnout")[i.turnout + 1], pos = 3)
  text(3, y.range[2] - 0.01, "FPTP candidacy", pos = 1)
  text(10, y.range[2] - 0.01, "On the party list", pos = 1)
  text(17, y.range[2] - 0.01, "On the party list", pos = 1)
  text(25, y.range[2] - 0.01, "FPTP candidacy", pos = 1)

  y.pos <- c(-.015, -.02)[plot.switch + 1]
  y.pos <- y.pos[!is.na(y.pos)]
  text(c(1:nrow(data.tv))[!is.na(data.tv$treat)], y.pos,
       paste0("(", data.tv$treat, ")")[!is.na(data.tv$treat)], cex = 0.8)

  dev.off()
}
```

### Effects with Jack-Knife

```{r}
for (i.vote in 1:2) {
  for (i.cand in 1:2) {
    data.tv <- all.results[all.results$i.turnout == 0 & all.results$i.spillover == 0 & all.results$i.tier == i.vote, ]

    if (i.vote == i.cand) {
      data.tv <- data.tv[substr(rownames(data.tv), 1, 5) == "treat", ]
    } else {
      data.tv <- data.tv[substr(rownames(data.tv), 1, 5) == "cross", ]
    }

    data.tv$lower.b <- data.tv$Estimate - 1.96 * data.tv$`Std. Error`
    data.tv$upper.b <- data.tv$Estimate + 1.96 * data.tv$`Std. Error`

    y.range <- range(c(data.tv$lower.b, data.tv$upper.b), na.rm = TRUE)
    y.range[1] <- y.range[1] - (y.range[2] - y.range[1]) * 0.1

    data.tv <- rbind(data.tv[1:3, ], NA, data.tv[4:nrow(data.tv), ])

    title <- paste0("All_Estimated_Effects_with_JK_replicated_",
                    c("cand", "list")[i.cand], "on", c("FPTP", "PR")[i.vote])
    title <- paste0(title, green.mask.suffix)

    pdf(file = paste0(legacy.fig.dir, "/", title, ".pdf"), width = 5, height = 5.5, pointsize = 13)

    plot(data.tv$Estimate, axes = FALSE,
         xlab = "", ylab = paste("Effect on", c("FPTP", "PR")[i.vote], "share"),
         ylim = y.range, xlim = c(0.5, nrow(data.tv) + .5), pch = 19, lwd = 1.5)

    data.tv$i.switch[is.na(data.tv$i.switch)] <- 0

    for (i.party in 1:nrow(data.tv)) {
      lines(c(i.party, i.party), c(data.tv$lower.b[i.party], data.tv$upper.b[i.party]), lty = 1, lwd = 2.5)
    }

    axis(1, labels = FALSE, at = c(1:3, 5:nrow(data.tv)))
    axis(2)
    abline(h = 0, lty = 2)

    data.tv$i.switch[data.tv$i.switch == 0] <- NA
    text(x = 1:nrow(data.tv), y = par("usr")[3] - (y.range[2] - y.range[1]) * 0.1,
         labels = c("All", "Major", "Minor", "", "w/o CDU/CSU", "w/o SPD", "w/o FDP", "w/o Left", "w/o Green", "w/o AfD"),
         xpd = NA, srt = 35, adj = 0.7, cex = 0.9)

    text(c(1:nrow(data.tv))[!is.na(data.tv$treat)], rep(y.range[1], nrow(data.tv))[!is.na(data.tv$treat)],
         paste0("(", data.tv$treat, ")")[!is.na(data.tv$treat)], cex = 0.8)

    dev.off()
  }
}
```
