---
title: "Visualization_FD_Results"
author: "Susumu Shikano"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




### Figures

```{r}
library(readxl)

results <- read_xlsx("Data/ModelSummaries.xlsx",sheet=2)

```


```{r}
# Define color palette
pacman::p_load(RColorBrewer)

party.colors <- #brewer.pal(9, "Set2")
                #c("#1E366F","#6D1E1E", "#6F6D1E", "#2B2B2B", "#B43104","#B5A200", "#993366","#3E6F2D", "#005F6B")
                c("#1D406E","#6E1D1D", "#6F6D1D", "#2B2B2B", "#B43004","#B59F00", "#9F3A62","#3E6E2C", "#005F6A")

# Add LaTeX font
library(extrafont)
loadfonts()


for (i.vote.d in 1:2){
  for (i.vote.i in 1:2){

    # Filter data by voting scenario
    data.tv <- as.data.frame(results[results$vote_d==i.vote.d & results$vote_i==i.vote.i & !is.na(results$vote_i),])
    rownames(data.tv) <- data.tv$Party
    
    # Calculate estimate, standard error, and confidence intervals
    p.estimate <- as.numeric(data.tv$Estimate)
    se <- as.numeric(data.tv$SE)                      # not the robust SE!!!
    lower.b <- p.estimate - 1.96* se
    upper.b <- p.estimate + 1.96* se
    
    # Set y-axis range based on confidence intervals
    y.range <- range(c(lower.b,upper.b))
    
    # Combine data into one data frame for visualization
    data.2 <- as.data.frame(cbind(p.estimate, se, lower.b, upper.b))
    rownames(data.2) <- data.tv$Party
    data.vis <- cbind(data.tv, data.2)
    
    # Set title based on voting scenario
    if (i.vote.d==1 & i.vote.i==1) title <- "Direktkandidatur auf Erststimmenergebnis"
    if (i.vote.d==1 & i.vote.i==2) title <- "Listenkandidatur auf Erststimmenergebnis"
    if (i.vote.d==2 & i.vote.i==1) title <- "Direktkandidatur auf Zweitstimmenergebnis"
    if (i.vote.d==2 & i.vote.i==2) title <- "Listenkandidatur auf Zweitstimmenergebnis"
    
    # Create PDF file for the current voting scenario
    pdf(file=paste0(title,".pdf"),
        width=12,
        height=9,
        pointsize = 13,
        family = "CM Roman")
    
    # Plot with colors and labels
    plot(p.estimate, axes=F,
    xlab="Spitzenkandidaten der Parteien", ylab="Unterschied im Stimmenanteil",
    ylim=y.range,
    #main=title,
    col=party.colors, lwd = 1.5)

    # Add vertical lines at each data point
    for (i.party in 1:length(p.estimate)){
    lines(c(i.party,i.party),
          c(lower.b[i.party],upper.b[i.party]),
            col=party.colors[i.party], lwd=1.5)
    points(i.party, p.estimate[i.party], col = "black", pch = 21)
}

    # Depending on voting scenario, manually add horizontal help lines
    # abline(h = 0, lty = 1)          # for all (optional)
    # abline(h = 0.002, lty = 2)      # "LK auf 1"
    # abline(h = 0.0025, lty = 2)     # "DK auf 2"
    # abline(h = 0.004, lty = 2)      # "LK auf 1"
     abline(h = 0.005, lty = 2)      # "DK auf 2" 
                                      # "LK auf 2"
    # abline(h = 0.006, lty = 2)      # "LK auf 1"
     abline(h = 0.0075, lty = 2)     # "DK auf 2" 
                                      # "LK auf 2"
     abline(h = 0.01, lty = 2)       # "DK auf 1"
                                      # "LK auf 2"
    # abline(h = 0.015, lty = 2)      # "DK auf 1"
     abline(h = 0.0175, lty = 2)     # "LK auf 2"
     abline(h = 0.02, lty = 2)       # "DK auf 1" 
                                      # "LK auf 2"
    # abline(h = 0.012, lty = 2)      # "LK auf 1" 
    
    # Add x-axis and y-axis labels
    axis(1, at=c(1:9), data.tv$Party, cex.axis=0.7)
    axis(2)
    
    # Add a frame
    box()

    dev.off() # close the current PDF file
    #embed_fonts(paste0(title,".pdf"), outfile=paste0(title,".pdf"))
    
    
    if (i.vote.d==1 & i.vote.i==1) data.vis.H1a <- data.vis
    if (i.vote.d==1 & i.vote.i==2) data.vis.H1b <- data.vis
    if (i.vote.d==2 & i.vote.i==2) data.vis.H2a <- data.vis
    if (i.vote.d==2 & i.vote.i==1) data.vis.H2b <- data.vis
 }
}
```


```{r}

# Create data
dat.Ha <- as.data.frame(rbind(data.vis.H1a[1,23], data.vis.H2a[1,23], data.vis.H1a[2,23], data.vis.H2a[2,23],data.vis.H1a[3,23], data.vis.H2a[3,23]))
names(dat.Ha) <- "p.estimate"
p.estimate <- dat.Ha$p.estimate
model <- dat.Ha$model <- c(1,1,2,2,3,3)
party <- dat.Ha$party <- c("Alle Parteien", "Alle Parteien", "CDU/CSU und SPD", "CDU/CSU und SPD", "Kleinere Parteien", "Kleinere Parteien")
hyp <- dat.Ha$hyp <- c("1a","2a","1a","2a","1a","2a")
se <- dat.Ha$se <- c(data.vis.H1a[1,24], data.vis.H2a[1,24], data.vis.H1a[2,24], data.vis.H2a[2,24],data.vis.H1a[3,24], data.vis.H2a[3,24])
lower.b <- dat.Ha$lower.b <- c(data.vis.H1a[1,25], data.vis.H2a[1,25], data.vis.H1a[2,25], data.vis.H2a[2,25],data.vis.H1a[3,25], data.vis.H2a[3,25])
upper.b <- dat.Ha$upper.b <- c(data.vis.H1a[1,26], data.vis.H2a[1,26], data.vis.H1a[2,26], data.vis.H2a[2,26],data.vis.H1a[3,26], data.vis.H2a[3,26])

y.range <- range(c(lower.b,upper.b))


party.colors <- c("#1D406E","#1D406E","#6E1D1D","#6E1D1D","#6F6D1D","#6F6D1D")

# pdf
pdf(file= "Ha_graphix.pdf",
        width=12,
        height=9,
        pointsize = 13,
        family = "CM Roman")

# Plot with colors and labels
plot(p.estimate, axes=F,
    xlab="Spitzenkandidaten der Parteien", ylab="Unterschied im Stimmenanteil",
    ylim=y.range,
    #main="Der Spitzenkandidateneffekt: Direktandidatur (je links) vs. Listenpräsenz (je rechts)",
    col=party.colors, lwd = 1.5)

# Add vertical lines at each data point
    for (i.party in 1:6){
    lines(c(i.party,i.party),
          c(lower.b[i.party],upper.b[i.party]),
            col=party.colors[i.party], lwd=1.5)
    points(i.party, p.estimate[i.party], col = "black", pch = 21)
}

# Depending on voting scenario, manually add horizontal help lines
  abline(h = 0, lty = 1)
  abline(h = 0.0038, lty = 2)
  abline(h = 0.0070, lty = 2)
  abline(h = 0.0139, lty = 2)
  abline(h = 0.0145, lty = 2)
  abline(h = 0.0179, lty = 2)
  abline(h = 0.0186, lty = 2)
     
# Add x-axis and y-axis labels
  axis(1, at=c(1:6), dat.Ha$party, cex.axis=0.7)
  axis(2)
    
# Add a frame
  box()

  dev.off() # close the current PDF file
```



```{r}
dat.Hb <- as.data.frame(rbind(data.vis.H1b[1,23], data.vis.H2b[1,23], data.vis.H1b[2,23], data.vis.H2b[2,23], data.vis.H1b[3,23], data.vis.H2b[3,23]))
names(dat.Hb) <- "p.estimate"
p.estimate <- dat.Hb$p.estimate
model <- dat.Hb$model <- c(1,1,2,2,3,3)
party <- dat.Hb$party <- c("Alle Parteien", "Alle Parteien", "CDU/CSU und SPD", "CDU/CSU und SPD", "Kleinere Parteien", "Kleinere Parteien")
hyp <- dat.Hb$hyp <- c("1b","2b","1b","2b","1b","2b")
se <- dat.Hb$se <- c(data.vis.H1b[1,24], data.vis.H2b[1,24], data.vis.H1b[2,24], data.vis.H2b[2,24], data.vis.H1b[3,24], data.vis.H2b[3,24])
lower.b <- dat.Hb$lower.b <- c(data.vis.H1b[1,25], data.vis.H2b[1,25], data.vis.H1b[2,25], data.vis.H2b[2,25], data.vis.H1b[3,25], data.vis.H2b[3,25])
upper.b <- dat.Hb$upper.b <- c(data.vis.H1b[1,26], data.vis.H2b[1,26], data.vis.H1b[2,26], data.vis.H2b[2,26], data.vis.H1b[3,26], data.vis.H2b[3,26])


y.range <- range(c(lower.b,upper.b))

party.colors <- c("#1D406E","#1D406E","#6E1D1D","#6E1D1D","#6F6D1D","#6F6D1D")

# pdf
pdf(file= "Hb_graphix.pdf",
        width=12,
        height=9,
        pointsize = 13,
        family = "CM Roman")

# Plot with colors and labels
plot(p.estimate, axes=F,
    xlab="Spitzenkandidaten der Parteien", ylab="Unterschied im Stimmenanteil",
    ylim=y.range,
    #main="Kontaminationseffekte: Direktandidatur (je links) vs. Listenpräsenz (je rechts)",
    col=party.colors, lwd = 1.5)

# Add vertical lines at each data point
    for (i.party in 1:6){
    lines(c(i.party,i.party),
          c(lower.b[i.party],upper.b[i.party]),
            col=party.colors[i.party], lwd=1.5)
    points(i.party, p.estimate[i.party], col = "black", pch = 21)
}

    # Depending on voting scenario, manually add horizontal help lines
     abline(h = 0, lty = 1)
     abline(h = 0.0042, lty = 2)
     abline(h = 0.0060, lty = 2)
     abline(h = 0.0114, lty = 2)
     abline(h = 0.0034, lty = 2)
     abline(h = 0.0021, lty = 2)
     abline(h = 0.0065, lty = 2)
    
    # Add x-axis and y-axis labels
    axis(1, at=c(1:6), dat.Ha$party, cex.axis=0.7)
    axis(2)
    
    # Add a frame
    box()

    dev.off() # close the current PDF file

```


